n_classes: 27
n_image_clusters:
  backbone: dino
  backbone_type: vit_base
  patch_size: 8
  dropout_p: 0.1
  pretrained_weights: null
  dim: 90
  extra_clusters: 0
  crf_max_iter: 10
  pos_w: 3
  pos_xy_std: 1
  bi_w: 4
  bi_xy_std: 67
  bi_rgb_std: 3
  lr: 0.0005
  cluster_lr: 0.005
  linear_lr: 0.005
  val_n_imgs: 3
  zero_clamp: true
  stabilize: false
  pointwise: true
  feature_samples: 11
  neg_samples: 5
  neg_inter_weight: 1.0
  pos_inter_weight: 0.5
  pos_intra_weight: 1.0
  neg_inter_shift: 0.3
  pos_inter_shift: 0.2
  pos_intra_shift: 0.35
cfg:
  backbone: dino
  backbone_type: vit_base
  patch_size: 8
  dropout_p: 0.1
  pretrained_weights: null
  dim: 90
  extra_clusters: 0
  crf_max_iter: 10
  pos_w: 3
  pos_xy_std: 1
  bi_w: 4
  bi_xy_std: 67
  bi_rgb_std: 3
  lr: 0.0005
  cluster_lr: 0.005
  linear_lr: 0.005
  val_n_imgs: 3
  zero_clamp: true
  stabilize: false
  pointwise: true
  feature_samples: 11
  neg_samples: 5
  neg_inter_weight: 1.0
  pos_inter_weight: 0.5
  pos_intra_weight: 1.0
  neg_inter_shift: 0.3
  pos_inter_shift: 0.2
  pos_intra_shift: 0.35
