model_path: "/home/tipriest/data/TerrainSeg/models/cocostuff27_vit_base_5.ckpt"
output_path: "/home/tipriest/data/TerrainSeg/models/stego_cocostuff27_vit_base_5_cluster_linear_fine_tuning.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~