image_dir: "/home/tipriest/data/TerrainSeg/RUGDTest"
output_root: "/home/tipriest/data/TerrainSeg/RUGDTest/outputs"
model_path: "/home/tipriest/data/TerrainSeg/models/epoch=5-step=4800.ckpt"
# model_path: "/root/catkin_ws/src/self_supervised_segmentation/models/FF_training_200.ckpt"
# model_path: "/root/catkin_ws/src/self_supervised_segmentation/models/cityscapes_vit_base_1.ckpt"
experiment_name: "forest_youtube_val"
resolution: 320

# Loader params
batch_size: 8
num_workers: 24

run_crf: True