image_dir: "/cluster/home/plibera/images"
output_root: "/cluster/home/plibera/outputs/preds"
model_path: "/cluster/home/plibera/self_supervised_segmentation/models/stego_cocostuff27_vit_base_5.ckpt"
experiment_name: "forest_youtube_val"
resolution: 320

# Loader params
batch_size: 8
num_workers: 24

run_crf: True