data_dir: "/cluster/scratch/plibera"
dataset_name: "robot_images"

# Paths tp stego models with given numbers of clusters. The models should have the same backbone and segmentation head weights (only differ in the clustering step)
model_paths: ["/cluster/scratch/plibera/checkpoints/saved/FF_training_10.ckpt", "/cluster/scratch/plibera/checkpoints/saved/FF_training_20.ckpt", "/cluster/scratch/plibera/checkpoints/saved/FF_training_40.ckpt",
              "/cluster/scratch/plibera/checkpoints/saved/FF_training_70.ckpt"] #, "/cluster/scratch/plibera/checkpoints/saved/FF_training_70.ckpt", "/cluster/scratch/plibera/checkpoints/saved/FF_training_100.ckpt"]
              # "/cluster/scratch/plibera/checkpoints/saved/FF_training_200.ckpt"]
stego_n_clusters: [10, 20, 40, 70]
cluster_stego_by_image: True
slic_n_clusters: [10, 20, 40, 70, 100]
slic_compactness: 10

output_root: "/cluster/home/plibera/outputs/wvn"
experiment_name: "robot_images_crf"
save_vis: True
save_plots: True
save_comparison_plots: True

resolution: 320
num_workers: 1

n_imgs: # Optionally, specify a number of batches in the shuffled dataset to calculate metrics on to save time
run_crf: True