data_dir: "/cluster/scratch/plibera"
dataset_name: "freiburg_forest_preprocessed_trav"

# Paths tp stego models with given numbers of clusters. The models should have the same backbone and segmentation head weights (only differ in the clustering step)
model_paths: ["/cluster/scratch/plibera/checkpoints/saved/FF_training_5.ckpt", "/cluster/scratch/plibera/checkpoints/saved/FF_training_10.ckpt", "/cluster/scratch/plibera/checkpoints/saved/FF_training_20.ckpt",
              "/cluster/scratch/plibera/checkpoints/saved/FF_training_40.ckpt", "/cluster/scratch/plibera/checkpoints/saved/FF_training_70.ckpt", "/cluster/scratch/plibera/checkpoints/saved/FF_training_100.ckpt",
              "/cluster/scratch/plibera/checkpoints/saved/FF_training_200.ckpt"]
stego_n_clusters: [5, 10, 20, 40, 70, 100, 200]
slic_n_clusters: [5, 10, 20, 40, 70, 100]
slic_compactness: 10

output_root: "/cluster/home/plibera/outputs/wvn"
experiment_name: "FF_val_crf"
save_vis: True

resolution: 320
num_workers: 1

n_imgs: # Optionally, specify a number of batches in the shuffled dataset to calculate metrics on to save time
run_crf: True