data_dir: "/cluster/scratch/plibera"
dataset_name: "freiburg_forest_preprocessed"

# Paths tp stego models with given numbers of clusters. The models should have the same backbone and segmentation head weights (only differ in the clustering step)
model_paths: []
stego_n_clusters: []
cluster_stego_by_image: False
slic_n_clusters: []
slic_compactness: 10

output_root: "/cluster/home/plibera/outputs/wvn"
experiment_name: "freiburg_forest_labels"
save_vis: True
save_plots: False
save_comparison_plots: False

resolution: 320
num_workers: 1

n_imgs: # Optionally, specify a number of batches in the shuffled dataset to calculate metrics on to save time
run_crf: True