data_dir: "/home/tipriest/data/TerrainSeg/hit_grass/VID_20220502_135318"
dataset_name: "3_cropped"
image_sets:
  - "train"
  - "val"

resolution: 224
batch_size: 96
num_workers: 24

num_neighbors: 30
