# Data and paths
model_path: #"/media/plibera/stego/models/stego_cocostuff27_vit_base_5.ckpt"
cmap: "turbo"
zero_mean: False # Mean normalize cosine similarity values in the displayed heatmap
zero_clamp: True # Clamp cosine similarity heatmap to 0



# Interactive correspondences plot
plot_correspondences_interactive: True
image_a_path: "/cluster/home/plibera/forest.png" 
image_b_path: # Can be omitted to generate self-correspondences for the first image
correspondence_output_dir: "/cluster/home/plibera"
display_resolution: 512


# Augmentations params for image B
brightness_factor: 1.0  # Non-negative, 1.0 for no change
contrast_factor: 1.0    # Non-negative, 1.0 for no change
saturation_factor: 1.0  # Non-negative, 1.0 for no change
hue_factor: 0.0         # [-0.5, 0.5], 0.0 for no change

gaussian_kernel_size: #13
gaussian_sigma: #2.0



# Precision-Recall curves plot
plot_pr: False
plot_backbone_pr: True
plot_stego_pr: False
data_dir: "/scratch/tmp.17524104.plibera"
dataset_name: "cocostuff_curated"
pr_output_dir: "/cluster/home/plibera/self_supervised_segmentation/results/pr"
pr_output_data_dir: "/cluster/scratch/plibera/results/pr"
additional_pr_curves: ["cocostuff_curated_DINO-B-8_336.pkl", "cocostuff_curated_DINO-B-16_336.pkl"] # Names if pickled PR data files to additionally display in the plot
pr_resolution: 336
batch_size: 8
num_workers: 24