data_dir: "/scratch/tmp.17610028.plibera"
dataset_name: "freiburg_forest_preprocessed_cropped"

checkpoint_dir: "/cluster/scratch/plibera/checkpoints/FF_training_500"
model_path: #"/cluster/home/plibera/self_supervised_segmentation/models/stego_cocostuff27_vit_base_5_cluster_fine_tuning.ckpt"


resolution: 224
num_classes: 500

num_workers: 24
batch_size: 32

scalar_log_freq: 1
max_steps: 5000
val_check_interval: 32

num_neighbors: 5

reset_clusters: False
extra_clusters: 0

# WandB
wandb_project: "stego"
wandb_name: "freiburg_forest_cropped_training_500"
wandb_log_model: "all"
