image_dir: "/home/tipriest/data/TerrainSeg/hit_grass/videos_preprocessed/VID_20220502_135318/imgs/train"
output_root: "/home/tipriest/data/TerrainSeg/hit_grass/videos_preprocessed/VID_20220502_135318/imgs/output"
model_path: "/home/tipriest/data/TerrainSeg/hit_grass/models/epoch=45-step=960.ckpt"
# model_path: "/root/catkin_ws/src/self_supervised_segmentation/models/FF_training_200.ckpt"
# model_path: "/root/catkin_ws/src/self_supervised_segmentation/models/cityscapes_vit_base_1.ckpt"
experiment_name: "hit_grass"
resolution: 320


video_path: "/home/tipriest/data/TerrainSeg/hit_grass/Videos/VID_20220502_135318.mp4"
output_video_path: "/home/tipriest/data/TerrainSeg/hit_grass/Videos/output.mp4"
# Loader params
batch_size: 8
num_workers: 24

run_crf: True