output_root: "/media/plibera/results/stego_og"
model_path: "/media/plibera/stego/saved_models/cocostuff27_vit_base_5.ckpt"
image_dir: "/media/cocostuff/imgs/val"
experiment_name: "cocostuff_val"
res: 320
batch_size: 8
num_workers: 24
use_ddp: False

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
