image_a_path: "/media/plibera/test_images/imgs/train/000000160970.jpg"
image_b_path: "/media/plibera/test_images/imgs/train/000000308677.jpg" # Can be omitted to generate self-correspondences for the first image
output_dir: "/media/plibera/results/correspondence"

arch: dino # Available models: ["dino"]

resolution: 512

# Augmentations params for image B
use_augmentations: False

brightness_factor: 1.0  # Non-negative, 1.0 for no change
contrast_factor: 1.0    # Non-negative, 1.0 for no change
saturation_factor: 1.0  # Non-negative, 1.0 for no change
hue_factor: 0.0         # [-0.5, 0.5], 0.0 for no change

use_gaussian_blur: False
gaussian_kernel_size: 13
gaussian_sigma: 2.0


# Model Params
extra_clusters: 0
use_true_labels: False
use_recalibrator: False
model_type: "vit_small"
use_fit_model: False
dino_feat_type: "feat"
projection_type: 
dino_patch_size: 8
granularity: 1
continuous: True
dim: 70
dropout: True
zero_clamp: True


pretrained_weights: ~